### ISSUE TITLE
Participantes como Contribuidores

### ISSUE THREAD

**Issue by jlsilva01** [DouglasKuerten/sistema-gestao-estacionamento#1]
Ola pessoal, onde estão os demais participantes do grupo cadastrados como contribuidores?
Nenhum cadastrado até este momento.

**Comment by GustavoTBett** [comment]
certo, já iremos colocar todos como participantes do projeto

**Comment by DouglasKuerten** [comment]
Todos foram convidados no dia da aula já, alguns ainda não aceitaram o convite
![image](https://github.com/DouglasKuerten/sistema-gestao-estacionamento/assets/100738618/721aab31-4856-486a-9786-6bbea79d63d2)
